const FETCH_RECIPES = "FETCH_RECIPES";
const FETCH_RECIPES_OK = "FETCH_RECIPES_OK";
const FETCH_RECIPES_ERROR = "FETCH_RECIPES_ERROR";

export { FETCH_RECIPES, FETCH_RECIPES_OK, FETCH_RECIPES_ERROR };
